//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySections
    {
        public int CompanyId { get; set; }
        public int SectionId { get; set; }
        public bool Active { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Sections Sections { get; set; }
    }
}
