//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIndexes
    {
        public int ProductId { get; set; }
        public byte IndexId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Indexes Indexes { get; set; }
    }
}
