<?xml version="1.0" encoding="utf-8"?><Database Name="OTC" Class="OTCDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MX-DF2K8APP02;Initial Catalog=OTC;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OTCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.plm_vwProductsByEdition" Member="plm_vwProductsByEdition">
    <Type Name="plm_vwProductsByEdition">
      <Column Name="CountryId" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="LabActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DivisionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DivisionName" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="DivisionShortName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DivisionActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProductDescription" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ProductActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PharmaFormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="PharmaFormActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EditionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberEdition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BarCode" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="EditionActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TypeInEdition" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Page" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NewProduct" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="BookActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfActiveSubstances" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfIndications" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Advertisements" Member="Advertisements">
    <Type Name="Advertisements">
      <Column Name="AdId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ImageFile" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Advertisements_EditionDivisionAds" Member="EditionDivisionAds" ThisKey="AdId" OtherKey="AdId" Type="EditionDivisionAds" />
    </Type>
  </Table>
  <Table Name="dbo.Symptoms" Member="Symptoms">
    <Type Name="Symptoms">
      <Column Name="SymptomId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Symptoms_ProductSymptoms" Member="ProductSymptoms" ThisKey="SymptomId" OtherKey="SymptomId" Type="ProductSymptoms" />
    </Type>
  </Table>
  <Table Name="dbo.ProductSymptoms" Member="ProductSymptoms">
    <Type Name="ProductSymptoms">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SymptomId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ProductSymptoms_EditionSymptoms" Member="EditionSymptoms" ThisKey="ProductId,SymptomId" OtherKey="ProductId,SymptomId" Type="EditionSymptoms" />
      <Association Name="Symptoms_ProductSymptoms" Member="Symptoms" ThisKey="SymptomId" OtherKey="SymptomId" Type="Symptoms" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductSubstances" Member="ProductSubstances">
    <Type Name="ProductSubstances">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActiveSubstanceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ActiveSubstances_ProductSubstances" Member="ActiveSubstances" ThisKey="ActiveSubstanceId" OtherKey="ActiveSubstanceId" Type="ActiveSubstances" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActiveSubstances" Member="ActiveSubstances">
    <Type Name="ActiveSubstances">
      <Column Name="ActiveSubstanceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubstanceKey" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="EnglishDescription" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Enunciative" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ActiveSubstances_ProductSubstances" Member="ProductSubstances" ThisKey="ActiveSubstanceId" OtherKey="ActiveSubstanceId" Type="ProductSubstances" />
    </Type>
  </Table>
  <Table Name="" Member="ProductByEdition">
    <Type Name="ProductByEdition">
      <Column Name="Brand" Type="System.String" CanBeNull="false" />
      <Column Name="Substances" Type="System.String" CanBeNull="false" />
      <Column Name="Description" Type="System.String" CanBeNull="false" />
      <Column Name="PharmaForm" Type="System.String" CanBeNull="false" />
      <Column Name="Division" Type="System.String" CanBeNull="false" />
      <Column Name="Pages" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="SymptomByEdition">
    <Type Name="SymptomByEdition">
      <Column Name="Symptom" Type="System.String" CanBeNull="false" />
      <Column Name="Page" Type="System.String" CanBeNull="false" />
      <Column Name="SymptomId" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="SubstanceByEdition">
    <Type Name="SubstanceByEdition">
      <Column Member="SubstanceId" Type="System.String" CanBeNull="false" />
      <Column Member="Substance" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.EditionDivisionAds" Member="EditionDivisionAds">
    <Type Name="EditionDivisionAds">
      <Column Name="AdId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DivisionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EditionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Page" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Advertisements_EditionDivisionAds" Member="Advertisements" ThisKey="AdId" OtherKey="AdId" Type="Advertisements" IsForeignKey="true" />
      <Association Name="Divisions_EditionDivisionAds" Member="Divisions" ThisKey="DivisionId" OtherKey="DivisionId" Type="Divisions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EditionSymptoms" Member="EditionSymptoms">
    <Type Name="EditionSymptoms">
      <Column Name="EditionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SymptomId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Page" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ProductSymptoms_EditionSymptoms" Member="ProductSymptoms" ThisKey="ProductId,SymptomId" OtherKey="ProductId,SymptomId" Type="ProductSymptoms" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Divisions" Member="Divisions">
    <Type Name="Divisions">
      <Column Name="DivisionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Divisions_EditionDivisionAds" Member="EditionDivisionAds" ThisKey="DivisionId" OtherKey="DivisionId" Type="EditionDivisionAds" />
      <Association Name="Divisions_Divisions" Member="Divisions2" ThisKey="DivisionId" OtherKey="ParentId" Type="Divisions" />
      <Association Name="Divisions_DivisionInformation" Member="DivisionInformation" ThisKey="DivisionId" OtherKey="DivisionId" Type="DivisionInformation" />
      <Association Name="Divisions_Divisions" Member="Divisions1" ThisKey="ParentId" OtherKey="DivisionId" Type="Divisions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DivisionInformation" Member="DivisionInformation">
    <Type Name="DivisionInformation">
      <Column Name="DivisionInfoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Image" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Suburb" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Web" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Divisions_DivisionInformation" Member="Divisions" ThisKey="DivisionId" OtherKey="DivisionId" Type="Divisions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="AdsByEdition">
    <Type Name="AdsByEdition">
      <Column Member="AdName" Type="System.String" CanBeNull="false" />
      <Column Member="Page" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.plm_dfGetPagesByProduct" Method="plm_dfGetPagesByProduct" IsComposable="true">
    <Parameter Name="productId" Type="System.Int32" DbType="Int" />
    <Parameter Name="editionId" Type="System.Int32" DbType="Int" />
    <Parameter Name="divisionId" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.plm_dfGetActiveSubsByProduct" Method="plm_dfGetActiveSubsByProduct" IsComposable="true">
    <Parameter Name="productId" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.plm_dfGetPharmaFormsByProductName" Method="plm_dfGetPharmaFormsByProductName" IsComposable="true">
    <!--<Parameter Name="editionId" Type="System.Int32" DbType="Int" />-->
    <Parameter Name="editionId" Type="System.Int32" DbType="Int" />
    <Parameter Name="brand" Type="System.Int32" DbType="VarChar(200)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.plm_dfProductsByPage" Method="plm_dfProductsByPage" IsComposable="true">
    <Parameter Name="editionId" Type="System.Int32" DbType="Int" />
    <Parameter Name="page" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.plm_dfGetPagesBySymptom" Method="plm_dfGetPagesBySymptom" IsComposable="true">
    <Parameter Name="symptomId" Type="System.Int32" DbType="Int" />
    <Parameter Name="editionId" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.plm_dfGetActiveSubstancesByProductBySubstance" Method="plm_dfGetActiveSubstancesByProductBySubstance" IsComposable="true">
    <Parameter Name="productId" Type="System.Int32" DbType="Int" />
    <Parameter Name="substanceId" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
</Database>