//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionClientProducts
    {
        public int EditionId { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public bool Validation { get; set; }
    
        public virtual ClientProducts ClientProducts { get; set; }
        public virtual Editions Editions { get; set; }
        public virtual ParticipantProducts ParticipantProducts { get; set; }
        public virtual EditionBookClientProducts EditionBookClientProducts { get; set; }
        public virtual Status Status { get; set; }
    }
}
