//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers
    {
        public Manufacturers()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ManufacturerId { get; set; }
        public string Manufacturer { get; set; }
        public bool Active { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
