//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalPacks
    {
        public ExternalPacks()
        {
            this.Presentations = new HashSet<Presentations>();
        }
    
        public int ExternalPackId { get; set; }
        public string ExternalPackName { get; set; }
        public bool Active { get; set; }
        public string True { get; set; }
    
        public virtual ICollection<Presentations> Presentations { get; set; }
    }
}
