//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrices
    {
        public int PresentationId { get; set; }
        public int BarCodeId { get; set; }
        public byte PriceSourceId { get; set; }
        public double Price { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual PriceSources PriceSources { get; set; }
        public virtual ProductBarCodes ProductBarCodes { get; set; }
    }
}
