//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBarCodes
    {
        public ProductBarCodes()
        {
            this.ProductPrices = new HashSet<ProductPrices>();
        }
    
        public int PresentationId { get; set; }
        public int BarCodeId { get; set; }
        public Nullable<decimal> AveragePrice { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool Active { get; set; }
    
        public virtual BarCodes BarCodes { get; set; }
        public virtual Presentations Presentations { get; set; }
        public virtual ICollection<ProductPrices> ProductPrices { get; set; }
    }
}
