//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductCategories = new HashSet<ProductCategories>();
            this.ProductPharmaForms = new HashSet<ProductPharmaForms>();
            this.ProductPharmaForms1 = new HashSet<ProductPharmaForms>();
        }
    
        public int ProductId { get; set; }
        public int CountryId { get; set; }
        public int LaboratoryId { get; set; }
        public byte AlphabetId { get; set; }
        public byte ProductTypeId { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public string SanitaryRegistry { get; set; }
        public bool Active { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Countries Countries1 { get; set; }
        public virtual ICollection<ProductCategories> ProductCategories { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual Alphabet Alphabet { get; set; }
        public virtual ICollection<ProductPharmaForms> ProductPharmaForms { get; set; }
        public virtual ICollection<ProductPharmaForms> ProductPharmaForms1 { get; set; }
        public virtual Laboratories Laboratories { get; set; }
        public virtual Laboratories Laboratories1 { get; set; }
    }
}
