//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectActivities()
        {
            this.BinnacleActivities = new HashSet<BinnacleActivities>();
        }
    
        public int ActivityId { get; set; }
        public int UserId { get; set; }
        public int ProjectId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public byte InvestedTime { get; set; }
        public string ActivityDescription { get; set; }
        public string Comment { get; set; }
        public int BinnacleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinnacleActivities> BinnacleActivities { get; set; }
        public virtual Binnacles Binnacles { get; set; }
        public virtual UserProjects UserProjects { get; set; }
    }
}
