//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountriesUser
    {
        public CountriesUser()
        {
            this.UserCountries = new HashSet<UserCountries>();
            this.Users = new HashSet<Users>();
        }
    
        public int CountryId { get; set; }
        public int RegionId { get; set; }
        public string CountryName { get; set; }
        public string ID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<UserCountries> UserCountries { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
