//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editions
    {
        public Editions()
        {
            this.EditionAttributes = new HashSet<EditionAttributes>();
            this.Editions1 = new HashSet<Editions>();
        }
    
        public int EditionId { get; set; }
        public byte EditionTypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int CountryId { get; set; }
        public int NumberEdition { get; set; }
        public string ISBN { get; set; }
        public string BarCode { get; set; }
        public bool Active { get; set; }
        public int BookId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<EditionAttributes> EditionAttributes { get; set; }
        public virtual ICollection<Editions> Editions1 { get; set; }
        public virtual Editions Editions2 { get; set; }
        public virtual Editions Editions11 { get; set; }
        public virtual Editions Editions3 { get; set; }
    }
}
