//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionPillBookAttributes
    {
        public EditionPillBookAttributes()
        {
            this.PillBookEncyclopedias = new HashSet<PillBookEncyclopedias>();
            this.PillBookAssociated = new HashSet<PillBookAssociated>();
        }
    
        public int PillBookId { get; set; }
        public int EditionId { get; set; }
        public int AttributeId { get; set; }
        public int AttributeGroupId { get; set; }
        public string Content { get; set; }
        public Nullable<byte> PillBookIconId { get; set; }
    
        public virtual EditionAttributeGroup EditionAttributeGroup { get; set; }
        public virtual PillBook PillBooks { get; set; }
        public virtual ICollection<PillBookEncyclopedias> PillBookEncyclopedias { get; set; }
        public virtual ICollection<PillBookAssociated> PillBookAssociated { get; set; }
        public virtual PillBookIcons PillBookIcons { get; set; }
    }
}
