//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICD
    {
        public ICD()
        {
            this.ICD1 = new HashSet<ICD>();
            this.ProductICD = new HashSet<ProductICD>();
            this.PillBookICD = new HashSet<PillBookICD>();
        }
    
        public int ICDId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ICDKey { get; set; }
        public string SpanishDescription { get; set; }
        public string EnglishDescription { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Level { get; set; }
    
        public virtual ICollection<ICD> ICD1 { get; set; }
        public virtual ICD ICD2 { get; set; }
        public virtual ICollection<ProductICD> ProductICD { get; set; }
        public virtual ICollection<PillBookICD> PillBookICD { get; set; }
    }
}
