//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillBooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plm_vwProductsByEdition
    {
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public int LaboratoryId { get; set; }
        public string LaboratoryName { get; set; }
        public bool LabActive { get; set; }
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public string DivisionShortName { get; set; }
        public bool DivisionActive { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public bool CategoryActive { get; set; }
        public Nullable<byte> ProductTypeId { get; set; }
        public string ProductType { get; set; }
        public int ProductId { get; set; }
        public string Brand { get; set; }
        public string SanitaryRegistry { get; set; }
        public string ProductDescription { get; set; }
        public string LabDescription { get; set; }
        public bool ProductActive { get; set; }
        public int PharmaFormId { get; set; }
        public string PharmaForm { get; set; }
        public string EnglishPharmaForm { get; set; }
        public bool PharmaActive { get; set; }
        public int EditionId { get; set; }
        public int NumberEdition { get; set; }
        public string ISBN { get; set; }
        public string BarCode { get; set; }
        public bool EditionActive { get; set; }
        public string TypeInEdition { get; set; }
        public string ModifiedContent { get; set; }
        public string Page { get; set; }
        public int NewProduct { get; set; }
        public int BriefProduct { get; set; }
        public int BookId { get; set; }
        public string BookName { get; set; }
        public bool BookActive { get; set; }
        public Nullable<int> NumberOfActiveSubstances { get; set; }
        public Nullable<int> NumberOfIndications { get; set; }
        public Nullable<int> NumberOfTherapeutics { get; set; }
        public Nullable<int> NumberOfOMSTherapeutics { get; set; }
        public string CountryCodes { get; set; }
    }
}
