//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.261
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEIADataAccessComponent.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=195.192.2.17;Initial Catalog=\"DEIA 21\";Persist Security Info=True;Use" +
            "r ID=sa;Password=t0m$0nl@t1n@")]
        public string DEIA_21ConnectionString1 {
            get {
                return ((string)(this["DEIA_21ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MX-DF2K8APP02;Initial Catalog=DEIA 21;Persist Security Info=True;User" +
            " ID=sa;Password=t0m$0nl@t1n@")]
        public string DEIA_21ConnectionString {
            get {
                return ((string)(this["DEIA_21ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MX-DF2K8APP02;Initial Catalog=\"DEIA 21\";Persist Security Info=True;Us" +
            "er ID=sa")]
        public string DEIA_21ConnectionString2 {
            get {
                return ((string)(this["DEIA_21ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MX-DF2K8APP02;Initial Catalog=\"DEIA 22\";Persist Security Info=True;Us" +
            "er ID=sa;Password=t0m$0nl@t1n@")]
        public string DEIA_22ConnectionString {
            get {
                return ((string)(this["DEIA_22ConnectionString"]));
            }
        }
    }
}
