//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisements
    {
        public Advertisements()
        {
            this.EditionSpecialityClientAdvers = new HashSet<EditionSpecialityClientAdvers>();
        }
    
        public int AdvertId { get; set; }
        public int Order { get; set; }
        public bool Active { get; set; }
        public string AdvertName { get; set; }
        public string BaseUrl { get; set; }
        public byte AdvertTypeId { get; set; }
    
        public virtual AdvertTypes AdvertTypes { get; set; }
        public virtual ICollection<EditionSpecialityClientAdvers> EditionSpecialityClientAdvers { get; set; }
    }
}
