//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddresses
    {
        public ClientAddresses()
        {
            this.ClientPhones = new HashSet<ClientPhones>();
        }
    
        public int ClientId { get; set; }
        public int AddressId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Addresses Addresses { get; set; }
        public virtual ICollection<ClientPhones> ClientPhones { get; set; }
    }
}
