//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProductSubstances
    {
        public ClientProductSubstances()
        {
            this.EditionClientMedicalProducts = new HashSet<EditionClientMedicalProducts>();
            this.ClientMedicalProductsBarCode = new HashSet<ClientMedicalProductsBarCode>();
        }
    
        public int ProductId { get; set; }
        public int PharmaFormId { get; set; }
        public int ActiveSubstanceId { get; set; }
        public int PresentationId { get; set; }
        public int ClientId { get; set; }
        public string RegisterSanitary { get; set; }
    
        public virtual ClientProducts ClientProducts { get; set; }
        public virtual ProductSubstances ProductSubstances { get; set; }
        public virtual ICollection<EditionClientMedicalProducts> EditionClientMedicalProducts { get; set; }
        public virtual ICollection<ClientMedicalProductsBarCode> ClientMedicalProductsBarCode { get; set; }
    }
}
