//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPhones
    {
        public string Number { get; set; }
        public string Lada { get; set; }
        public int ClientPhoneId { get; set; }
        public byte PhoneTypeId { get; set; }
        public bool Active { get; set; }
        public int ClientId { get; set; }
        public int AddressId { get; set; }
    
        public virtual ClientAddresses ClientAddresses { get; set; }
        public virtual PhoneTypes PhoneTypes { get; set; }
    }
}
