//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionClients
    {
        public EditionClients()
        {
            this.EditionClientSpecialities = new HashSet<EditionClientSpecialities>();
            this.ClientBrands = new HashSet<ClientBrands>();
        }
    
        public int EditionId { get; set; }
        public int ClientId { get; set; }
        public string Page { get; set; }
        public byte ClientTypeId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ClientTypes ClientTypes { get; set; }
        public virtual Editions Editions { get; set; }
        public virtual ICollection<EditionClientSpecialities> EditionClientSpecialities { get; set; }
        public virtual ICollection<ClientBrands> ClientBrands { get; set; }
    }
}
