//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesSizes
    {
        public ImagesSizes()
        {
            this.EditionProductShotSizes = new HashSet<EditionProductShotSizes>();
            this.BrandImageSizes = new HashSet<BrandImageSizes>();
        }
    
        public byte ImageSizeId { get; set; }
        public string ImageSize { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<EditionProductShotSizes> EditionProductShotSizes { get; set; }
        public virtual ICollection<BrandImageSizes> BrandImageSizes { get; set; }
    }
}
