//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeafHomogeneousCategories
    {
        public LeafHomogeneousCategories()
        {
            this.ClientProductLeafCategories = new HashSet<ClientProductLeafCategories>();
        }
    
        public int HomogeneousCategoryId { get; set; }
        public int LeafCategoryId { get; set; }
    
        public virtual LeafCategories LeafCategories { get; set; }
        public virtual HomogeneousCategories HomogeneousCategories { get; set; }
        public virtual ICollection<ClientProductLeafCategories> ClientProductLeafCategories { get; set; }
    }
}
