//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeafCategories
    {
        public LeafCategories()
        {
            this.LeafHomogeneousCategories = new HashSet<LeafHomogeneousCategories>();
        }
    
        public int LeafCategoryId { get; set; }
        public string LeafCategory { get; set; }
        public byte Level { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<LeafHomogeneousCategories> LeafHomogeneousCategories { get; set; }
    }
}
