//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menues
    {
        public Menues()
        {
            this.WebPageSectionMenues = new HashSet<WebPageSectionMenues>();
        }
    
        public int MenuId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MenuName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<WebPageSectionMenues> WebPageSectionMenues { get; set; }
    }
}
