//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLMUsers : DbContext
    {
        public PLMUsers()
            : base("name=PLMUsers")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLogs> ActivityLogs { get; set; }
        public virtual DbSet<ActivitySessions> ActivitySessions { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<ApplicationUsers> ApplicationUsers { get; set; }
        public virtual DbSet<CountriesUser> CountriesUser { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tables> Tables { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserCountries> UserCountries { get; set; }
        public virtual DbSet<Menues> Menues { get; set; }
        public virtual DbSet<WebPages> WebPages { get; set; }
        public virtual DbSet<WebPageSectionMenues> WebPageSectionMenues { get; set; }
        public virtual DbSet<WebPageSections> WebPageSections { get; set; }
        public virtual DbSet<WebSections> WebSections { get; set; }
        public virtual DbSet<RolMenues> RolMenues { get; set; }
    }
}
