//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiaNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPageSections
    {
        public WebPageSections()
        {
            this.WebPageSectionMenues = new HashSet<WebPageSectionMenues>();
        }
    
        public int WebPageId { get; set; }
        public byte WebSectionId { get; set; }
        public bool Active { get; set; }
    
        public virtual WebPages WebPages { get; set; }
        public virtual ICollection<WebPageSectionMenues> WebPageSectionMenues { get; set; }
        public virtual WebSections WebSections { get; set; }
    }
}
