//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Cities = new HashSet<Cities>();
            this.States = new HashSet<States>();
            this.Divisions = new HashSet<Divisions>();
            this.Products = new HashSet<Products>();
            this.Editions = new HashSet<Editions>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<byte> CountryCode { get; set; }
        public string ID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual ICollection<States> States { get; set; }
        public virtual ICollection<Divisions> Divisions { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Editions> Editions { get; set; }
    }
}
