//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public Operations()
        {
            this.OperationRoles = new HashSet<OperationRoles>();
            this.ActivityLogs = new HashSet<ActivityLogs>();
        }
    
        public int OperationId { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<OperationRoles> OperationRoles { get; set; }
        public virtual ICollection<ActivityLogs> ActivityLogs { get; set; }
    }
}
