//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCrops
    {
        public int ProductId { get; set; }
        public int CropId { get; set; }
        public string Substance { get; set; }
    
        public virtual Crops Crops { get; set; }
        public virtual Products Products { get; set; }
    }
}
