//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeds
    {
        public Seeds()
        {
            this.PProductSeeds = new HashSet<PProductSeeds>();
        }
    
        public int SeedId { get; set; }
        public string SeedName { get; set; }
        public string ScientificName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<PProductSeeds> PProductSeeds { get; set; }
    }
}
