//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace AgroBusinessLogicComponent._PLMTracking {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPLMLogs", Namespace="http://tempuri.org/")]
    public partial class PLMLogs : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback addLogActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback logsAddActivitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback addLogParentActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback logsAddParentActivitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback addTrackingActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback addTrackingActivitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPLMTrackingActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPLMTrackingActivitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPLMTrackingParentActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPLMTrackingParentActivitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPLMTrackingSearchActivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPLMTrackingSearchActivitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPLMTrackingCalculatorsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PLMLogs() {
            this.Url = global::AgroBusinessLogicComponent.Properties.Settings.Default.AgroBusinessLogicComponent_com_plmconnection_www_PLMLogs;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addLogActivityCompletedEventHandler addLogActivityCompleted;
        
        /// <remarks/>
        public event logsAddActivitiesCompletedEventHandler logsAddActivitiesCompleted;
        
        /// <remarks/>
        public event addLogParentActivityCompletedEventHandler addLogParentActivityCompleted;
        
        /// <remarks/>
        public event logsAddParentActivitiesCompletedEventHandler logsAddParentActivitiesCompleted;
        
        /// <remarks/>
        public event addTrackingActivityCompletedEventHandler addTrackingActivityCompleted;
        
        /// <remarks/>
        public event addTrackingActivitiesCompletedEventHandler addTrackingActivitiesCompleted;
        
        /// <remarks/>
        public event addPLMTrackingActivityCompletedEventHandler addPLMTrackingActivityCompleted;
        
        /// <remarks/>
        public event addPLMTrackingActivitiesCompletedEventHandler addPLMTrackingActivitiesCompleted;
        
        /// <remarks/>
        public event addPLMTrackingParentActivityCompletedEventHandler addPLMTrackingParentActivityCompleted;
        
        /// <remarks/>
        public event addPLMTrackingParentActivitiesCompletedEventHandler addPLMTrackingParentActivitiesCompleted;
        
        /// <remarks/>
        public event addPLMTrackingSearchActivityCompletedEventHandler addPLMTrackingSearchActivityCompleted;
        
        /// <remarks/>
        public event addPLMTrackingSearchActivitiesCompletedEventHandler addPLMTrackingSearchActivitiesCompleted;
        
        /// <remarks/>
        public event addPLMTrackingCalculatorsCompletedEventHandler addPLMTrackingCalculatorsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addLogActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addLogActivity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PSE_TrackingListInfo track) {
            this.Invoke("addLogActivity", new object[] {
                        track});
        }
        
        /// <remarks/>
        public void addLogActivityAsync(PSE_TrackingListInfo track) {
            this.addLogActivityAsync(track, null);
        }
        
        /// <remarks/>
        public void addLogActivityAsync(PSE_TrackingListInfo track, object userState) {
            if ((this.addLogActivityOperationCompleted == null)) {
                this.addLogActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddLogActivityOperationCompleted);
            }
            this.InvokeAsync("addLogActivity", new object[] {
                        track}, this.addLogActivityOperationCompleted, userState);
        }
        
        private void OnaddLogActivityOperationCompleted(object arg) {
            if ((this.addLogActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addLogActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/logsAddActivities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PSELogsBusinessEntities")]
        public PSE_TrackingListInfo[] logsAddActivities([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PSELogsBusinessEntities")] PSE_TrackingListInfo[] trackList) {
            object[] results = this.Invoke("logsAddActivities", new object[] {
                        trackList});
            return ((PSE_TrackingListInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void logsAddActivitiesAsync(PSE_TrackingListInfo[] trackList) {
            this.logsAddActivitiesAsync(trackList, null);
        }
        
        /// <remarks/>
        public void logsAddActivitiesAsync(PSE_TrackingListInfo[] trackList, object userState) {
            if ((this.logsAddActivitiesOperationCompleted == null)) {
                this.logsAddActivitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogsAddActivitiesOperationCompleted);
            }
            this.InvokeAsync("logsAddActivities", new object[] {
                        trackList}, this.logsAddActivitiesOperationCompleted, userState);
        }
        
        private void OnlogsAddActivitiesOperationCompleted(object arg) {
            if ((this.logsAddActivitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logsAddActivitiesCompleted(this, new logsAddActivitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addLogParentActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addLogParentActivity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PSE_TrackingParentInfo parentTrack) {
            this.Invoke("addLogParentActivity", new object[] {
                        parentTrack});
        }
        
        /// <remarks/>
        public void addLogParentActivityAsync(PSE_TrackingParentInfo parentTrack) {
            this.addLogParentActivityAsync(parentTrack, null);
        }
        
        /// <remarks/>
        public void addLogParentActivityAsync(PSE_TrackingParentInfo parentTrack, object userState) {
            if ((this.addLogParentActivityOperationCompleted == null)) {
                this.addLogParentActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddLogParentActivityOperationCompleted);
            }
            this.InvokeAsync("addLogParentActivity", new object[] {
                        parentTrack}, this.addLogParentActivityOperationCompleted, userState);
        }
        
        private void OnaddLogParentActivityOperationCompleted(object arg) {
            if ((this.addLogParentActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addLogParentActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/logsAddParentActivities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void logsAddParentActivities([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PSELogsBusinessEntities")] PSE_TrackingParentInfo[] parentTrackList) {
            this.Invoke("logsAddParentActivities", new object[] {
                        parentTrackList});
        }
        
        /// <remarks/>
        public void logsAddParentActivitiesAsync(PSE_TrackingParentInfo[] parentTrackList) {
            this.logsAddParentActivitiesAsync(parentTrackList, null);
        }
        
        /// <remarks/>
        public void logsAddParentActivitiesAsync(PSE_TrackingParentInfo[] parentTrackList, object userState) {
            if ((this.logsAddParentActivitiesOperationCompleted == null)) {
                this.logsAddParentActivitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogsAddParentActivitiesOperationCompleted);
            }
            this.InvokeAsync("logsAddParentActivities", new object[] {
                        parentTrackList}, this.logsAddParentActivitiesOperationCompleted, userState);
        }
        
        private void OnlogsAddParentActivitiesOperationCompleted(object arg) {
            if ((this.logsAddParentActivitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logsAddParentActivitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addTrackingActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addTrackingActivity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Info_TrackingListInfo track) {
            this.Invoke("addTrackingActivity", new object[] {
                        track});
        }
        
        /// <remarks/>
        public void addTrackingActivityAsync(Info_TrackingListInfo track) {
            this.addTrackingActivityAsync(track, null);
        }
        
        /// <remarks/>
        public void addTrackingActivityAsync(Info_TrackingListInfo track, object userState) {
            if ((this.addTrackingActivityOperationCompleted == null)) {
                this.addTrackingActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddTrackingActivityOperationCompleted);
            }
            this.InvokeAsync("addTrackingActivity", new object[] {
                        track}, this.addTrackingActivityOperationCompleted, userState);
        }
        
        private void OnaddTrackingActivityOperationCompleted(object arg) {
            if ((this.addTrackingActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addTrackingActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addTrackingActivities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addTrackingActivities([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/InfoLogsBusinessEntries")] Info_TrackingListInfo[] trackList) {
            this.Invoke("addTrackingActivities", new object[] {
                        trackList});
        }
        
        /// <remarks/>
        public void addTrackingActivitiesAsync(Info_TrackingListInfo[] trackList) {
            this.addTrackingActivitiesAsync(trackList, null);
        }
        
        /// <remarks/>
        public void addTrackingActivitiesAsync(Info_TrackingListInfo[] trackList, object userState) {
            if ((this.addTrackingActivitiesOperationCompleted == null)) {
                this.addTrackingActivitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddTrackingActivitiesOperationCompleted);
            }
            this.InvokeAsync("addTrackingActivities", new object[] {
                        trackList}, this.addTrackingActivitiesOperationCompleted, userState);
        }
        
        private void OnaddTrackingActivitiesOperationCompleted(object arg) {
            if ((this.addTrackingActivitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addTrackingActivitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addPLMTrackingActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPLMTrackingActivity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TrackingListInfo track) {
            this.Invoke("addPLMTrackingActivity", new object[] {
                        track});
        }
        
        /// <remarks/>
        public void addPLMTrackingActivityAsync(TrackingListInfo track) {
            this.addPLMTrackingActivityAsync(track, null);
        }
        
        /// <remarks/>
        public void addPLMTrackingActivityAsync(TrackingListInfo track, object userState) {
            if ((this.addPLMTrackingActivityOperationCompleted == null)) {
                this.addPLMTrackingActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPLMTrackingActivityOperationCompleted);
            }
            this.InvokeAsync("addPLMTrackingActivity", new object[] {
                        track}, this.addPLMTrackingActivityOperationCompleted, userState);
        }
        
        private void OnaddPLMTrackingActivityOperationCompleted(object arg) {
            if ((this.addPLMTrackingActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPLMTrackingActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addPLMTrackingActivities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPLMTrackingActivities([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")] TrackingListInfo[] trackList) {
            this.Invoke("addPLMTrackingActivities", new object[] {
                        trackList});
        }
        
        /// <remarks/>
        public void addPLMTrackingActivitiesAsync(TrackingListInfo[] trackList) {
            this.addPLMTrackingActivitiesAsync(trackList, null);
        }
        
        /// <remarks/>
        public void addPLMTrackingActivitiesAsync(TrackingListInfo[] trackList, object userState) {
            if ((this.addPLMTrackingActivitiesOperationCompleted == null)) {
                this.addPLMTrackingActivitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPLMTrackingActivitiesOperationCompleted);
            }
            this.InvokeAsync("addPLMTrackingActivities", new object[] {
                        trackList}, this.addPLMTrackingActivitiesOperationCompleted, userState);
        }
        
        private void OnaddPLMTrackingActivitiesOperationCompleted(object arg) {
            if ((this.addPLMTrackingActivitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPLMTrackingActivitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addPLMTrackingParentActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPLMTrackingParentActivity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TrackingParentInfo parentTrack) {
            this.Invoke("addPLMTrackingParentActivity", new object[] {
                        parentTrack});
        }
        
        /// <remarks/>
        public void addPLMTrackingParentActivityAsync(TrackingParentInfo parentTrack) {
            this.addPLMTrackingParentActivityAsync(parentTrack, null);
        }
        
        /// <remarks/>
        public void addPLMTrackingParentActivityAsync(TrackingParentInfo parentTrack, object userState) {
            if ((this.addPLMTrackingParentActivityOperationCompleted == null)) {
                this.addPLMTrackingParentActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPLMTrackingParentActivityOperationCompleted);
            }
            this.InvokeAsync("addPLMTrackingParentActivity", new object[] {
                        parentTrack}, this.addPLMTrackingParentActivityOperationCompleted, userState);
        }
        
        private void OnaddPLMTrackingParentActivityOperationCompleted(object arg) {
            if ((this.addPLMTrackingParentActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPLMTrackingParentActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addPLMTrackingParentActivities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPLMTrackingParentActivities([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")] TrackingParentInfo[] parentTrackList) {
            this.Invoke("addPLMTrackingParentActivities", new object[] {
                        parentTrackList});
        }
        
        /// <remarks/>
        public void addPLMTrackingParentActivitiesAsync(TrackingParentInfo[] parentTrackList) {
            this.addPLMTrackingParentActivitiesAsync(parentTrackList, null);
        }
        
        /// <remarks/>
        public void addPLMTrackingParentActivitiesAsync(TrackingParentInfo[] parentTrackList, object userState) {
            if ((this.addPLMTrackingParentActivitiesOperationCompleted == null)) {
                this.addPLMTrackingParentActivitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPLMTrackingParentActivitiesOperationCompleted);
            }
            this.InvokeAsync("addPLMTrackingParentActivities", new object[] {
                        parentTrackList}, this.addPLMTrackingParentActivitiesOperationCompleted, userState);
        }
        
        private void OnaddPLMTrackingParentActivitiesOperationCompleted(object arg) {
            if ((this.addPLMTrackingParentActivitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPLMTrackingParentActivitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addPLMTrackingSearchActivity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPLMTrackingSearchActivity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SearchTrackInfo track) {
            this.Invoke("addPLMTrackingSearchActivity", new object[] {
                        track});
        }
        
        /// <remarks/>
        public void addPLMTrackingSearchActivityAsync(SearchTrackInfo track) {
            this.addPLMTrackingSearchActivityAsync(track, null);
        }
        
        /// <remarks/>
        public void addPLMTrackingSearchActivityAsync(SearchTrackInfo track, object userState) {
            if ((this.addPLMTrackingSearchActivityOperationCompleted == null)) {
                this.addPLMTrackingSearchActivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPLMTrackingSearchActivityOperationCompleted);
            }
            this.InvokeAsync("addPLMTrackingSearchActivity", new object[] {
                        track}, this.addPLMTrackingSearchActivityOperationCompleted, userState);
        }
        
        private void OnaddPLMTrackingSearchActivityOperationCompleted(object arg) {
            if ((this.addPLMTrackingSearchActivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPLMTrackingSearchActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addPLMTrackingSearchActivities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPLMTrackingSearchActivities([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")] SearchTrackInfo[] trackList) {
            this.Invoke("addPLMTrackingSearchActivities", new object[] {
                        trackList});
        }
        
        /// <remarks/>
        public void addPLMTrackingSearchActivitiesAsync(SearchTrackInfo[] trackList) {
            this.addPLMTrackingSearchActivitiesAsync(trackList, null);
        }
        
        /// <remarks/>
        public void addPLMTrackingSearchActivitiesAsync(SearchTrackInfo[] trackList, object userState) {
            if ((this.addPLMTrackingSearchActivitiesOperationCompleted == null)) {
                this.addPLMTrackingSearchActivitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPLMTrackingSearchActivitiesOperationCompleted);
            }
            this.InvokeAsync("addPLMTrackingSearchActivities", new object[] {
                        trackList}, this.addPLMTrackingSearchActivitiesOperationCompleted, userState);
        }
        
        private void OnaddPLMTrackingSearchActivitiesOperationCompleted(object arg) {
            if ((this.addPLMTrackingSearchActivitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPLMTrackingSearchActivitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPLMLogs/addPLMTrackingCalculators", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPLMTrackingCalculators([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CalculatorsLogsBusinessEntries")] ResultTrackingInfo[] trackList) {
            this.Invoke("addPLMTrackingCalculators", new object[] {
                        trackList});
        }
        
        /// <remarks/>
        public void addPLMTrackingCalculatorsAsync(ResultTrackingInfo[] trackList) {
            this.addPLMTrackingCalculatorsAsync(trackList, null);
        }
        
        /// <remarks/>
        public void addPLMTrackingCalculatorsAsync(ResultTrackingInfo[] trackList, object userState) {
            if ((this.addPLMTrackingCalculatorsOperationCompleted == null)) {
                this.addPLMTrackingCalculatorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPLMTrackingCalculatorsOperationCompleted);
            }
            this.InvokeAsync("addPLMTrackingCalculators", new object[] {
                        trackList}, this.addPLMTrackingCalculatorsOperationCompleted, userState);
        }
        
        private void OnaddPLMTrackingCalculatorsOperationCompleted(object arg) {
            if ((this.addPLMTrackingCalculatorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPLMTrackingCalculatorsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PSE_TrackingParentInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PSELogsBusinessEntities")]
    public partial class PSE_TrackingListInfo {
        
        private string attributesField;
        
        private string codeStringField;
        
        private int editionIdField;
        
        private bool editionIdFieldSpecified;
        
        private int entityIdField;
        
        private bool entityIdFieldSpecified;
        
        private string jsonFormatField;
        
        private bool replicateField;
        
        private bool replicateFieldSpecified;
        
        private System.Nullable<System.DateTime> searchDateField;
        
        private bool searchDateFieldSpecified;
        
        private string searchParametersField;
        
        private byte searchTypeIdField;
        
        private bool searchTypeIdFieldSpecified;
        
        private byte sourceIdField;
        
        private bool sourceIdFieldSpecified;
        
        private int trackIdField;
        
        private bool trackIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodeString {
            get {
                return this.codeStringField;
            }
            set {
                this.codeStringField = value;
            }
        }
        
        /// <comentarios/>
        public int EditionId {
            get {
                return this.editionIdField;
            }
            set {
                this.editionIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EditionIdSpecified {
            get {
                return this.editionIdFieldSpecified;
            }
            set {
                this.editionIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public int EntityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityIdSpecified {
            get {
                return this.entityIdFieldSpecified;
            }
            set {
                this.entityIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JsonFormat {
            get {
                return this.jsonFormatField;
            }
            set {
                this.jsonFormatField = value;
            }
        }
        
        /// <comentarios/>
        public bool Replicate {
            get {
                return this.replicateField;
            }
            set {
                this.replicateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplicateSpecified {
            get {
                return this.replicateFieldSpecified;
            }
            set {
                this.replicateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchDate {
            get {
                return this.searchDateField;
            }
            set {
                this.searchDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchDateSpecified {
            get {
                return this.searchDateFieldSpecified;
            }
            set {
                this.searchDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchParameters {
            get {
                return this.searchParametersField;
            }
            set {
                this.searchParametersField = value;
            }
        }
        
        /// <comentarios/>
        public byte SearchTypeId {
            get {
                return this.searchTypeIdField;
            }
            set {
                this.searchTypeIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchTypeIdSpecified {
            get {
                return this.searchTypeIdFieldSpecified;
            }
            set {
                this.searchTypeIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public byte SourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceIdSpecified {
            get {
                return this.sourceIdFieldSpecified;
            }
            set {
                this.sourceIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public int TrackId {
            get {
                return this.trackIdField;
            }
            set {
                this.trackIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrackIdSpecified {
            get {
                return this.trackIdFieldSpecified;
            }
            set {
                this.trackIdFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CalculatorsLogsBusinessEntries")]
    public partial class ResultTrackingInfo {
        
        private int calculatorIdField;
        
        private bool calculatorIdFieldSpecified;
        
        private string codeStringField;
        
        private string parametersField;
        
        private string resultField;
        
        private System.Nullable<System.DateTime> resultDateField;
        
        private bool resultDateFieldSpecified;
        
        private byte sourceIdField;
        
        private bool sourceIdFieldSpecified;
        
        private int trackIdField;
        
        private bool trackIdFieldSpecified;
        
        /// <comentarios/>
        public int CalculatorId {
            get {
                return this.calculatorIdField;
            }
            set {
                this.calculatorIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CalculatorIdSpecified {
            get {
                return this.calculatorIdFieldSpecified;
            }
            set {
                this.calculatorIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodeString {
            get {
                return this.codeStringField;
            }
            set {
                this.codeStringField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ResultDate {
            get {
                return this.resultDateField;
            }
            set {
                this.resultDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultDateSpecified {
            get {
                return this.resultDateFieldSpecified;
            }
            set {
                this.resultDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public byte SourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceIdSpecified {
            get {
                return this.sourceIdFieldSpecified;
            }
            set {
                this.sourceIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public int TrackId {
            get {
                return this.trackIdField;
            }
            set {
                this.trackIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrackIdSpecified {
            get {
                return this.trackIdFieldSpecified;
            }
            set {
                this.trackIdFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")]
    public partial class SearchTrackInfo {
        
        private string attributeGroupKeyField;
        
        private Info_TrackingListInfo[] childrenInfoTrackingInfoField;
        
        private TrackingListInfo[] childrenTrackingInfoField;
        
        private string codeStringField;
        
        private int entityIdField;
        
        private bool entityIdFieldSpecified;
        
        private string iSBNField;
        
        private string jsonFormatField;
        
        private bool replicateField;
        
        private bool replicateFieldSpecified;
        
        private System.Nullable<System.DateTime> searchDateField;
        
        private bool searchDateFieldSpecified;
        
        private string searchParametersField;
        
        private byte searchTypeIdField;
        
        private bool searchTypeIdFieldSpecified;
        
        private byte sourceIdField;
        
        private bool sourceIdFieldSpecified;
        
        private int trackIdField;
        
        private bool trackIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AttributeGroupKey {
            get {
                return this.attributeGroupKeyField;
            }
            set {
                this.attributeGroupKeyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/InfoLogsBusinessEntries")]
        public Info_TrackingListInfo[] ChildrenInfoTrackingInfo {
            get {
                return this.childrenInfoTrackingInfoField;
            }
            set {
                this.childrenInfoTrackingInfoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TrackingListInfo[] ChildrenTrackingInfo {
            get {
                return this.childrenTrackingInfoField;
            }
            set {
                this.childrenTrackingInfoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodeString {
            get {
                return this.codeStringField;
            }
            set {
                this.codeStringField = value;
            }
        }
        
        /// <comentarios/>
        public int EntityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityIdSpecified {
            get {
                return this.entityIdFieldSpecified;
            }
            set {
                this.entityIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JsonFormat {
            get {
                return this.jsonFormatField;
            }
            set {
                this.jsonFormatField = value;
            }
        }
        
        /// <comentarios/>
        public bool Replicate {
            get {
                return this.replicateField;
            }
            set {
                this.replicateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplicateSpecified {
            get {
                return this.replicateFieldSpecified;
            }
            set {
                this.replicateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchDate {
            get {
                return this.searchDateField;
            }
            set {
                this.searchDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchDateSpecified {
            get {
                return this.searchDateFieldSpecified;
            }
            set {
                this.searchDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchParameters {
            get {
                return this.searchParametersField;
            }
            set {
                this.searchParametersField = value;
            }
        }
        
        /// <comentarios/>
        public byte SearchTypeId {
            get {
                return this.searchTypeIdField;
            }
            set {
                this.searchTypeIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchTypeIdSpecified {
            get {
                return this.searchTypeIdFieldSpecified;
            }
            set {
                this.searchTypeIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public byte SourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceIdSpecified {
            get {
                return this.sourceIdFieldSpecified;
            }
            set {
                this.sourceIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public int TrackId {
            get {
                return this.trackIdField;
            }
            set {
                this.trackIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrackIdSpecified {
            get {
                return this.trackIdFieldSpecified;
            }
            set {
                this.trackIdFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/InfoLogsBusinessEntries")]
    public partial class Info_TrackingListInfo {
        
        private string codeStringField;
        
        private int entityIdField;
        
        private bool entityIdFieldSpecified;
        
        private string jSONFormatField;
        
        private System.Nullable<int> parentIdField;
        
        private bool parentIdFieldSpecified;
        
        private bool replicateField;
        
        private bool replicateFieldSpecified;
        
        private System.Nullable<System.DateTime> searchDateField;
        
        private bool searchDateFieldSpecified;
        
        private string searchParametersField;
        
        private byte searchTypeIdField;
        
        private bool searchTypeIdFieldSpecified;
        
        private byte sourceIdField;
        
        private bool sourceIdFieldSpecified;
        
        private int trackIdField;
        
        private bool trackIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodeString {
            get {
                return this.codeStringField;
            }
            set {
                this.codeStringField = value;
            }
        }
        
        /// <comentarios/>
        public int EntityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityIdSpecified {
            get {
                return this.entityIdFieldSpecified;
            }
            set {
                this.entityIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JSONFormat {
            get {
                return this.jSONFormatField;
            }
            set {
                this.jSONFormatField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParentIdSpecified {
            get {
                return this.parentIdFieldSpecified;
            }
            set {
                this.parentIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Replicate {
            get {
                return this.replicateField;
            }
            set {
                this.replicateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplicateSpecified {
            get {
                return this.replicateFieldSpecified;
            }
            set {
                this.replicateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchDate {
            get {
                return this.searchDateField;
            }
            set {
                this.searchDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchDateSpecified {
            get {
                return this.searchDateFieldSpecified;
            }
            set {
                this.searchDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchParameters {
            get {
                return this.searchParametersField;
            }
            set {
                this.searchParametersField = value;
            }
        }
        
        /// <comentarios/>
        public byte SearchTypeId {
            get {
                return this.searchTypeIdField;
            }
            set {
                this.searchTypeIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchTypeIdSpecified {
            get {
                return this.searchTypeIdFieldSpecified;
            }
            set {
                this.searchTypeIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public byte SourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceIdSpecified {
            get {
                return this.sourceIdFieldSpecified;
            }
            set {
                this.sourceIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public int TrackId {
            get {
                return this.trackIdField;
            }
            set {
                this.trackIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrackIdSpecified {
            get {
                return this.trackIdFieldSpecified;
            }
            set {
                this.trackIdFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackingParentInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")]
    public partial class TrackingListInfo {
        
        private string attributeGroupKeyField;
        
        private string codeStringField;
        
        private int entityIdField;
        
        private bool entityIdFieldSpecified;
        
        private string iSBNField;
        
        private string jsonFormatField;
        
        private bool replicateField;
        
        private bool replicateFieldSpecified;
        
        private System.Nullable<System.DateTime> searchDateField;
        
        private bool searchDateFieldSpecified;
        
        private string searchParametersField;
        
        private byte searchTypeIdField;
        
        private bool searchTypeIdFieldSpecified;
        
        private byte sourceIdField;
        
        private bool sourceIdFieldSpecified;
        
        private int trackIdField;
        
        private bool trackIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AttributeGroupKey {
            get {
                return this.attributeGroupKeyField;
            }
            set {
                this.attributeGroupKeyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodeString {
            get {
                return this.codeStringField;
            }
            set {
                this.codeStringField = value;
            }
        }
        
        /// <comentarios/>
        public int EntityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityIdSpecified {
            get {
                return this.entityIdFieldSpecified;
            }
            set {
                this.entityIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JsonFormat {
            get {
                return this.jsonFormatField;
            }
            set {
                this.jsonFormatField = value;
            }
        }
        
        /// <comentarios/>
        public bool Replicate {
            get {
                return this.replicateField;
            }
            set {
                this.replicateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplicateSpecified {
            get {
                return this.replicateFieldSpecified;
            }
            set {
                this.replicateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchDate {
            get {
                return this.searchDateField;
            }
            set {
                this.searchDateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchDateSpecified {
            get {
                return this.searchDateFieldSpecified;
            }
            set {
                this.searchDateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchParameters {
            get {
                return this.searchParametersField;
            }
            set {
                this.searchParametersField = value;
            }
        }
        
        /// <comentarios/>
        public byte SearchTypeId {
            get {
                return this.searchTypeIdField;
            }
            set {
                this.searchTypeIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SearchTypeIdSpecified {
            get {
                return this.searchTypeIdFieldSpecified;
            }
            set {
                this.searchTypeIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public byte SourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceIdSpecified {
            get {
                return this.sourceIdFieldSpecified;
            }
            set {
                this.sourceIdFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public int TrackId {
            get {
                return this.trackIdField;
            }
            set {
                this.trackIdField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrackIdSpecified {
            get {
                return this.trackIdFieldSpecified;
            }
            set {
                this.trackIdFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLMLogsBusinessEntries")]
    public partial class TrackingParentInfo : TrackingListInfo {
        
        private TrackingListInfo[] childrenTrackingInfoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TrackingListInfo[] ChildrenTrackingInfo {
            get {
                return this.childrenTrackingInfoField;
            }
            set {
                this.childrenTrackingInfoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PSELogsBusinessEntities")]
    public partial class PSE_TrackingParentInfo : PSE_TrackingListInfo {
        
        private PSE_TrackingListInfo[] childrenTrackingInfoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PSE_TrackingListInfo[] ChildrenTrackingInfo {
            get {
                return this.childrenTrackingInfoField;
            }
            set {
                this.childrenTrackingInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addLogActivityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void logsAddActivitiesCompletedEventHandler(object sender, logsAddActivitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logsAddActivitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logsAddActivitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PSE_TrackingListInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PSE_TrackingListInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addLogParentActivityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void logsAddParentActivitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addTrackingActivityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addTrackingActivitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addPLMTrackingActivityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addPLMTrackingActivitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addPLMTrackingParentActivityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addPLMTrackingParentActivitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addPLMTrackingSearchActivityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addPLMTrackingSearchActivitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addPLMTrackingCalculatorsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591