//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantProducts
    {
        public int EditionId { get; set; }
        public int DivisionId { get; set; }
        public int CategoryId { get; set; }
        public int ProductId { get; set; }
        public int PharmaFormId { get; set; }
        public string HTMLContent { get; set; }
        public string Page { get; set; }
        public string XMLContent { get; set; }
        public Nullable<byte> ContentTypeId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Editions Editions { get; set; }
    }
}
