//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductSubstances = new HashSet<ProductSubstances>();
            this.ProductAgrochemicalUses = new HashSet<ProductAgrochemicalUses>();
            this.ProductCrops = new HashSet<ProductCrops>();
            this.ProductSeeds = new HashSet<ProductSeeds>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Register { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> LaboratoryId { get; set; }
        public bool Active { get; set; }
        public int AccessId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<ProductSubstances> ProductSubstances { get; set; }
        public virtual ICollection<ProductAgrochemicalUses> ProductAgrochemicalUses { get; set; }
        public virtual ICollection<ProductCrops> ProductCrops { get; set; }
        public virtual ICollection<ProductSeeds> ProductSeeds { get; set; }
    }
}
