//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agronet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeds
    {
        public Seeds()
        {
            this.ProductSeeds = new HashSet<ProductSeeds>();
        }
    
        public int SeedId { get; set; }
        public string SeedName { get; set; }
        public string ScientificName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ProductSeeds> ProductSeeds { get; set; }
    }
}
