//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPharmaForms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductPharmaForms()
        {
            this.ProductCategories = new HashSet<ProductCategories>();
        }
    
        public int PharmaFormId { get; set; }
        public int ProductId { get; set; }
        public bool Active { get; set; }
        public string ReferenceUrl { get; set; }
    
        public virtual PharmaceuticalForms PharmaceuticalForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategories> ProductCategories { get; set; }
        public virtual Products Products { get; set; }
        public virtual Products Products1 { get; set; }
    }
}
